-- Main Organization Table
CREATE TABLE IF NOT EXISTS cosc320_whed_org (
    org_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    global_id VARCHAR(17) UNIQUE,
    parent_org_id INT UNSIGNED,
    alias_id INT UNSIGNED NOT NULL DEFAULT 0,
    org_name VARCHAR(160) NOT NULL,
    branch_name VARCHAR(160) NOT NULL,
    inst_name_english VARCHAR(160) NOT NULL,
    branch_name_english VARCHAR(160) NOT NULL,
    country_code CHAR(2),
    state_code CHAR(2),
    state_id INT UNSIGNED,
    branch_id INT UNSIGNED,
    org_type_code CHAR(2),
    inst_name_alt VARCHAR(160),
    inst_acronym VARCHAR(50),
    inst_class_code CHAR(2),
    inst_funding_type_code CHAR(2),
    inst_type_id INT UNSIGNED,
    religion_code CHAR(2),
    student_body CHAR(1),
    logo VARCHAR(50),
    date_accredited DATE,
    partnership VARCHAR(50),
    comment TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INT UNSIGNED,
    is_warning BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    needs_update BOOLEAN NOT NULL DEFAULT FALSE,
    is_learning BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (org_id),
    INDEX idx_alias_id (alias_id),
    INDEX idx_org_name (org_name),
    INDEX idx_country_code (country_code),
    INDEX idx_state_code (state_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;