-- Main Organization Table
CREATE TABLE IF NOT EXISTS cosc320_whed_org (
    org_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    global_id VARCHAR(17) DEFAULT NULL,
    parent_org_id MEDIUMINT UNSIGNED DEFAULT NULL,
    alias_id MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
    family TINYINT UNSIGNED NOT NULL DEFAULT '0',
    org_name VARCHAR(160) NOT NULL DEFAULT '',
    branch_name VARCHAR(160) NOT NULL DEFAULT '',
    inst_name_english VARCHAR(160) NOT NULL DEFAULT '',
    branch_name_english VARCHAR(160) NOT NULL DEFAULT '',
    country_code CHAR(2) DEFAULT NULL,
    state_code CHAR(2) DEFAULT NULL,
    state_id MEDIUMINT UNSIGNED DEFAULT NULL,
    branch_id MEDIUMINT UNSIGNED DEFAULT NULL,
    org_type_code CHAR(2) DEFAULT NULL,
    inst_name_alt VARCHAR(160) DEFAULT NULL,
    inst_acronym VARCHAR(50) DEFAULT NULL,
    inst_class_code CHAR(2) DEFAULT NULL,
    inst_funding_type_code CHAR(2) DEFAULT NULL,
    inst_type_id MEDIUMINT UNSIGNED DEFAULT NULL,
    religion_code CHAR(2) DEFAULT NULL,
    student_body CHAR(1) DEFAULT NULL,
    logo VARCHAR(50) DEFAULT NULL,
    web_update_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    comment TEXT,
    partnership VARCHAR(50) DEFAULT NULL,
    is_warning BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    needs_update BOOLEAN NOT NULL DEFAULT FALSE,
    is_learning BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    updated_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    user_id MEDIUMINT UNSIGNED DEFAULT NULL,


    PRIMARY KEY (org_id),
    UNIQUE KEY (global_id),
    INDEX idx_alias_id (alias_id),
    INDEX idx_family (family),
    INDEX idx_org_name (org_name),
    INDEX idx_country_code (country_code),
    INDEX idx_state_code (state_code),
    INDEX idx_state_id (state_id),
    INDEX idx_inst_class_code (inst_class_code),
    INDEX idx_inst_funding_type_code (inst_funding_type_code),
    INDEX idx_parent_org_id(parent_org_id),
    INDEX idx_org_type_code (org_type_code),
    INDEX idx_religion_code (religion_code),
    INDEX idx_inst_type_id (inst_type_id),
    INDEX idx_user_id (user_id),
    FULLTEXT KEY org_name_full (org_name, inst_name_english, inst_name_alt, inst_acronym)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;