CREATE TABLE IF NOT EXISTS cosc320_whed_statesystem (
    state_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    academic_year_start INT DEFAULT 0,
    academic_year_end INT DEFAULT 0,
    entry_age VARCHAR(30) DEFAULT NULL,
    exit_age VARCHAR(30) DEFAULT NULL,
    school_system_description TEXT,
    higher_education_system_description TEXT,
    information_source TEXT,
    authority_in_charge TEXT,
    non_university_level_alternative_access TEXT,
    non_university_level_admission_test TEXT,
    non_university_level_other_requirements TEXT,
    non_university_level_numerus_clausus TEXT,
    university_level_alternative_access TEXT,
    university_level_admission_test TEXT,
    university_level_other_requirements TEXT,
    university_level_numerus_clausus TEXT,
    foreign_students_definition TEXT,
    foreign_students_quotas TEXT,
    foreign_students_admission_requirements TEXT,
    foreign_students_entry_regulations TEXT,
    foreign_students_health_requirements TEXT,
    foreign_students_language_proficiency TEXT,
    foreign_students_individual_institution_decision TINYINT(1) DEFAULT 0,
    foreign_students_central_body_decision TINYINT(1) DEFAULT 0,
    recognition_bodies_system_description TEXT,
    recognition_bodies_other_info_sources TEXT,
    recognition_bodies_non_university_level_studies TEXT,
    recognition_bodies_university_level_studies TEXT,
    recognition_bodies_postgraduate_level_studies TEXT,
    recognition_bodies_profession TEXT,
    student_support_home TINYINT(1) DEFAULT 0,
    student_support_home_amount DOUBLE DEFAULT 0,
    student_support_home_currency_code VARCHAR(4) DEFAULT NULL,
    student_support_foreign TINYINT(1) DEFAULT 0,
    student_support_foreign_amount DOUBLE DEFAULT 0,
    student_support_foreign_currency_code VARCHAR(4) DEFAULT NULL,
    student_support_foreign_details TEXT,
    transport_road ENUM('yes', 'no', 'unknown') DEFAULT 'unknown',
    transport_rail ENUM('yes', 'no', 'unknown') DEFAULT 'unknown',
    transport_air ENUM('yes', 'no', 'unknown') DEFAULT 'unknown',
    transport_foreign ENUM('yes', 'no', 'unknown') DEFAULT 'unknown',
    finance_average_living_cost INT DEFAULT 0,
    finance_average_living_cost_currency_code VARCHAR(4) DEFAULT NULL,
    finance_minimum_tuition_fee INT DEFAULT 0,
    finance_minimum_tuition_fee_currency_code VARCHAR(4) DEFAULT NULL,
    finance_maximum_tuition_fee INT DEFAULT 0,
    finance_maximum_tuition_fee_currency_code VARCHAR(4) DEFAULT NULL,
    finance_minimum_tuition_fee_foreign INT DEFAULT 0,
    finance_minimum_tuition_fee_foreign_currency_code VARCHAR(4) DEFAULT NULL,
    finance_maximum_tuition_fee_foreign INT DEFAULT 0,
    finance_maximum_tuition_fee_foreign_currency_code VARCHAR(4) DEFAULT NULL,
    input_date TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    major_update_date TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    minor_update_date TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    major_update_date_dp TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    record_history LONGTEXT NOT NULL,
    user_id MEDIUMINT UNSIGNED DEFAULT NULL,
    higher_education_teacher_training TEXT,
    distance_higher_education TEXT,
    update_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,
    web_update_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    comment TEXT,
    PRIMARY KEY (state_id),
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;