CREATE TABLE IF NOT EXISTS cosc320_whed_lex_fos (
  fos_code VARCHAR(6) NOT NULL,
  fos_level INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  fos_level_1 VARCHAR(160) DEFAULT NULL,
  fos_level_2 VARCHAR(160) DEFAULT NULL,
  fos_level_3 VARCHAR(160) DEFAULT NULL,
  fos_display VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (fos_code),
  UNIQUE KEY uk_fos_display (fos_display)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;