CREATE TABLE cosc320_whed_data_provider (
    provider_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    state_id MEDIUMINT UNSIGNED,
    dp_type_contact TINYINT UNSIGNED NOT NULL DEFAULT 0,
    dp_org_name VARCHAR(160),
    dp_name VARCHAR(100),
    dp_street TEXT NOT NULL,
    dp_city VARCHAR(60),
    dp_province VARCHAR(60),
    dp_post_code VARCHAR(40),
    dp_email VARCHAR(100),
    dp_email_copy VARCHAR(100),
    dp_status TINYINT UNSIGNED NOT NULL DEFAULT 0,
    dp_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,
    dp_control VARCHAR(32) NOT NULL DEFAULT '',
    date_sent TIMESTAMP NULL DEFAULT NULL,
    date_deadline TIMESTAMP NULL DEFAULT NULL,
    date_accessed TIMESTAMP NULL DEFAULT NULL,
    date_modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    date_reminder TIMESTAMP NULL DEFAULT NULL,
    date_returned TIMESTAMP NULL DEFAULT NULL,
    date_validated TIMESTAMP NULL DEFAULT NULL,
    reminder_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    reminder_history TEXT,
    PRIMARY KEY (provider_id),
    UNIQUE KEY (dp_control),
    UNIQUE KEY (state_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;