INSERT INTO cosc320_whed_org (
    org_id,
    global_id,
    parent_org_id,
    alias_id,
    org_name,
    branch_name,
    inst_name_english,
    branch_name_english,
    country_code,
    state_code,
    state_id,
    branch_id,
    org_type_code,
    inst_name_alt,
    inst_acronym,
    inst_class_code,
    inst_funding_type_code,
    inst_type_id,
    religion_code,
    student_body,
    logo,
    date_accredited,
    partnership,
    comment,
    created_at,
    updated_at,
    user_id,
    is_warning,
    is_deleted,
    needs_update,
    is_learning
)
SELECT
    OrgID,
    GlobalID,
    iParentOrgID,
    AliasID,
    OrgName,
    iBranchName,
    InstNameEnglish,
    iBranchNameEnglish,
    CountryCode,
    StateCode,
    StateID,
    BranchID,
    OrgTypeCode,
    InstNameAlt,
    InstAcronym,
    InstClassCode,
    InstFundingTypeCode,
    sInstTypeID,
    ReligionCode,
    iStudentBody,
    iLogo,
    CASE 
        WHEN DateAccredited REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN STR_TO_DATE(DateAccredited, '%Y-%m-%d')
        ELSE NULL
    END,
    iPartnership,
    iComment,
    NOW() AS created_at,
    NOW() AS updated_at,
    UserID,
    iWarning != 0,
    iDelete != 0,
    iUpdate != 0,
    iLearning != 0
FROM
    whed_org;

